version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT}:80"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      WIT_API_KEY_ENGLISH: "${WIT_API_KEY_ENGLISH}"
    env_file:
      - .env

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/initialize-db.sh:/docker-entrypoint-initdb.d/initialize-db.sh
    env_file:
      - .env

volumes:
  db_data:
